### ISSUE TITLE
Compute Nodes Immediately Enter 'Drain' State after completing a single job

### ISSUE THREAD

**Issue by stephen-thomas** [aws-samples/aws-plugin-for-slurm#10]
Output of sinfo -R
```
REASON               USER      TIMESTAMP           NODELIST
Low socket*core*thre root      2019-05-07T18:16:10 ip-10-0-1-[6-7]
```

Slurm_nodes.conf
`NodeName=ip-10-0-1-[6-12] CPUs=4 RealMemory=32000 Feature=us-west-1a State=Cloud`

I  am running on r5.2xlarge which has 4 vCPU. Should my CPU change to 2 in slurm_nodes.conf to reflect the number of physical CPUs?

**Comment by elgalu** [comment]
How did you solve this @stephen-thomas ?

**Comment by stephen-thomas** [comment]
@elgalu I learned how to use kubernetes

**Comment by stephen-thomas** [comment]
I'm kidding (although not really), back when we used this plugin I think I learned to do everything in terms of vCPUs, so I kept it as is at 4.
