### ISSUE TITLE
Attach shared filesystem

### ISSUE THREAD

**Issue by elyall** [aws-samples/aws-plugin-for-slurm#15]
I would like to save the stdout, stderr, and output data files to a filesystem I can access once the job is complete. It seems the advice is to leave /nfs for slurm config only. Is there a simple enough way to attach a shared filesystem, such as an EFS? 

@malaval plugin-v2 is great, particularly the Cloud Formation template, but this is a big hang up for me. Can you help with elaborating on this in the documentation?

**Comment by elyall** [comment]
Would creating an EFS (`fs-12345678`) and a corresponding access point (`fsap-12345678`) on the same VPC, followed by adding the following lines to the Launch Template ([e.g.](https://github.com/aws-samples/aws-plugin-for-slurm/blob/48e08c32e0906e308784877496b133ce99e35e45/template.yaml#L209)) work? 
```
mkdir /localmountpoint
mount -t efs -o tls,accesspoint=fsap-12345678 fs-12345678: /localmountpoint
```

**Comment by malaval** [comment]
@elyall Thanks for your message. You could start by creating a stack using the CloudFormation [template](https://github.com/aws-samples/aws-plugin-for-slurm/blob/plugin-v2/template.yaml) that I provide. Once the stack is created, you can log on to the headnode and browse the scripts folder (`/nfs/slurm/etc/aws`) to see the content of configuration files, or look at the Slurm configuration file (`/nfs/slurm/etc/slurm.conf`). If you have additional questions that the README did not help answer, feel free to let me know.

Regarding the shared storage, I will speak for the plugin-v2: Yes, you use a separate file share for logs, or you could use the same NFS share in the headnode (`/nfs/slurm` is the home folder for Slurm, you could use `/nfs/something` for job results).

To mount a EFS file share, access points are optional. You could directly mount the EFS file share with:

```
mount -t efs -o tls fs-12345678:/ /nfs
```

**Comment by elyall** [comment]
Thanks for the help. I was able to direct job output to a folder on nfs with `sudo mkdir /nfs/logs; chown -R ec2-user:ec2-user /nfs/logs` and `#SBATCH --output=/nfs/logs/slurm-%j.log`. Still working on where I will put my code and job results so that all nodes can access it.

**Comment by malaval** [comment]
Have you tried putting the code in a shared folder (e.g. `/nfs/code`) that all nodes can access, and set the current working directory with `--chdir` when launching the job? You should refer to the DESCRIPTION section of the [sbatch](https://slurm.schedmd.com/sbatch.html) which further describes what files Slurm copies or moves, and what it is up to users to do.

**Comment by elyall** [comment]
Thanks again. For now I'm using `/nfs/` to store code, but I will have to use a more scalable solution like EFS in the future due to nfs having a size limit. Here's my code:
```shell
sudo mkdir /nfs/code
sudo chown -R ec2-user:ec2-user /nfs/code
cd /nfs/code
python3 -m venv VENV-NAME
source VENV-NAME/bin/activate
pip3 install --upgrade -r requirements.txt
```
