### ISSUE TITLE
Failure to describe instances results in failed jobs

### ISSUE THREAD

**Issue by elyall** [aws-samples/aws-plugin-for-slurm#16]
@malaval in your plugin-v2, sporadically I will initiate a job (one that requires spinning up resources), and the job will fail with the same error when trying to "describe instances". Below is an example from `/var/log/slurm_plugin.log`. EC2 console shows that the instances are spun up, but not named. As well they are never taken down by cron. Do you think adding short pause somewhere would fix this to compensate for lag in spinning up the instances? If so, where would I add this in `template.yaml`?

> 2020-10-23 18:18:57,546 - resume - INFO - Hostlist: aws-node[0-2]
2020-10-23 18:18:59,468 - resume - ERROR - Failed to describe instances i-0170ad984d19605a7, i-02d9d1b04ed4967a0, i-0fe1b4ec0d61d2ebc: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance IDs 'i-0170ad984d19605a7, i-02d9d1b04ed4967a0, i-0fe1b4ec0d61d2ebc' do not exist

**Comment by malaval** [comment]
@elyall Thanks for the feedback. Indeed, there could have been an issue with DescribeInstances due to eventual consistency. I updated `resume.py` to retry 3 times if describe_instances returned an error. Can you please let me know if that solved the issue?

**Comment by elyall** [comment]
It has yet to reappear and seems to be fixed. Thanks!
