### ISSUE TITLE
Multiple SubnetIds

### ISSUE THREAD

**Issue by bollig** [aws-samples/aws-plugin-for-slurm#19]
Encountered this error testing multiple SubnetIds. The README does state that subnets need to be in different AZs (I had two in 1 AZ).  However, the error message below is not clear that "duplicate instance pools" refers to SubnetIds in the same AZ. 

```
2020-12-05 19:27:20,108 - resume - ERROR - Failed to launch nodes for partition=aws and nodegroup=node - An error occurred
 (InvalidFleetConfig) when calling the CreateFleet operation: The fleet configuration contains duplicate instance pools.
```

**Comment by bollig** [comment]
Plugin-v2

**Comment by malaval** [comment]
Hello, thanks for your message. The README already included "List of subnets where EC2 instances can be launched for this node group. If you provide multiple subnets, they must be in different availability zones". However, I just appended "or the `CreateFleet` request may return the error message *The fleet configuration contains duplicate instance pools*" to make it clear.
