### ISSUE TITLE
Need "export" in /etc/profile.d/slurm.sh

### ISSUE THREAD

**Issue by bollig** [aws-samples/aws-plugin-for-slurm#20]
https://github.com/aws-samples/aws-plugin-for-slurm/blob/46ff2e62334e482b36bed51e4b8af582667631c0/template.yaml#L422

If I salloc resources, once it clears any slurm command like sinfo throws this error:
![image](https://user-images.githubusercontent.com/187202/103833291-43c74e00-5046-11eb-9fd4-ee1079504cc1.png)

If i exit out of the salloc, it works as expected.

Fixed by adding export, and adjusting the SLURM_CONF value (dropped extra /slurm/ dir):  

```
export SLURM_HOME=/nfs/slurm
export SLURM_CONF=$SLURM_HOME/etc/slurm.conf
export PATH=$SLURM_HOME/bin:$PATH
```

**Comment by malaval** [comment]
Hi Evan, thanks for flagging this out. I edited `template.yaml`, which should solve the issue. Please let me know otherwise, or I let you close the issue.
