### ISSUE TITLE
Newer version of slurm needs additional libs installed

### ISSUE THREAD

**Issue by jxuamazon** [aws-samples/aws-plugin-for-slurm#24]
using slurm version 21.x , slurmrestd failed to start with ["Unable to find plugin: serializer/json"?]

Fix, add the following in the post_install before compiling slurm. 
yum install –y epel-release
yum-config-manager --enable epel
yum install -y libyaml http-parser-devel json-c-devel

**Comment by amrragab8080** [comment]
merged the [PR#25](https://github.com/aws-samples/aws-plugin-for-slurm/pull/25)
