### ISSUE TITLE
RESOURCE NOT CREATED AWS::CloudFormation::WaitCondition

### ISSUE THREAD

**Issue by byba1990** [aws-samples/aws-plugin-for-slurm#4]
Dear all,

I'm new in AWS and I've problem in the creation of a stack. Indeed, I followed the instructions in:

https://aws.amazon.com/it/blogs/compute/deploying-a-burstable-and-event-driven-hpc-cluster-on-aws-using-slurm-part-1/

but, at the end, the stack continued to have the state CREATE_IN_PROGRESS. I checked the resources and the only resources IN_PROGRESS (other resources were created) is:

AWS::CloudFormation::WaitCondition

Any suggestions, please?

Thank you for your time.
Best regards,

Christian

**Comment by amrragab8080** [comment]
Thank you for trying it out, that is expected, unless it ends in a timeout error the WaitCondition is waiting for a signal from the SLURM headnode that it finished installing the assets, it takes time as we are compiling SLURM.

**Comment by byba1990** [comment]
Ok, thank you for your replay. But I waited more than 20 minutes and it goes in a timeout error. Do you have suggestions, please?
Thank you for your time.
Best regards,

Christian

**Comment by amrragab8080** [comment]
Reprovision the stack and log into the headnode once its created. If any errors pop up you can see it with `journalctl -f ` it could also be possible to get a System Log from the EC2 console and errors may show up there. following the journal will be more verbose.

Once you do that paste the end of the log here and we can see what the error is.

**Comment by byba1990** [comment]
Hi,

I'm new in AWS and I don't know how I can log the headnode and launch the command "journalctl -f". Could you provide some indications, please? However, I post in the following line the detail about the failure for AWS::CloudFormation::WaitCondition :

CREATE_FAILED | AWS::CloudFormation::WaitCondition | SlurmManagementEC2WaitCondition | Failed to receive 1 resource signal(s) within the specified duration

Thank your for your time.
Regards,

Christian

**Comment by amrragab8080** [comment]
During Cloudformation, you will see an entry for the EC2 instance that refers to the SLURM management node. Once its up in your EC2 Console you can connect to it through ssh.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html

**Comment by byba1990** [comment]
Hi,

If I go in my EC2 console, I see the instance created with Stack. The problem is the instance will stop, after few seconds that it starts (In "Status Check", it is in "Initializing" state when the instance run for short time.) 

![instance1](https://user-images.githubusercontent.com/45231195/54742902-eb9a3000-4bc2-11e9-80c1-75e422077bd9.png)







In this way, I can't access to instance with ssh and I don't know why the instance has this problem, nevertheless the instance creation is ok from Stack:


![stack_creation3](https://user-images.githubusercontent.com/45231195/54742721-7890b980-4bc2-11e9-9088-5791d223b077.png)
![stack_creation2](https://user-images.githubusercontent.com/45231195/54742722-7890b980-4bc2-11e9-8fa8-b5b0d76dc683.png)
![stack_creation1](https://user-images.githubusercontent.com/45231195/54742723-7890b980-4bc2-11e9-83fa-b44e9af24bde.png)





Christian

**Comment by amrragab8080** [comment]
When an EC2 is created it starts in the initialized state, in a few moments it will reach running state in which you can ssh onto and run the journalctl command. Suggest reading up on the basics of EC2 before attempting to run this cloudformation stack. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

**Comment by byba1990** [comment]
Dear Amr,

Ok thank you for your information about EC2. However I tried to log onto when it is in running state without success. I used ssh with linux terminal and I didn't receive replay but ssh stays pending.  
To check If I have problem with ssh, I used the same key with an instance that I created independently from Stack: I didn't have problem in that case.

Regards,

Christian

NB: I attach the running state of the instance created with Stack
![initializePend](https://user-images.githubusercontent.com/45231195/54759535-93792300-4bee-11e9-8f71-84c0e644e782.png)

**Comment by amrragab8080** [comment]
In the CF stack it should ask you which key you want to use from the drop down menu, that key should be the same as what you use. Without seeing the error stack can you send me a screenshot of the s3 bucket contents where you are sourcing all the scripts?

**Comment by byba1990** [comment]
Yes, I use the same key. I attached the screenshot of the S3 bucket contents: folder, files and file content

![bucket_content2](https://user-images.githubusercontent.com/45231195/54765032-1606e000-4bf9-11e9-9994-0824d7658ba7.png)
![bucket_content](https://user-images.githubusercontent.com/45231195/54765035-169f7680-4bf9-11e9-8770-646b6c2ff466.png)
![yml_content](https://user-images.githubusercontent.com/45231195/54765033-1606e000-4bf9-11e9-85e7-3ceb1a1f5a71.png)

Thank you for your time.
Regards,

Christian

**Comment by byba1990** [comment]
Dear amrragab8080,

any other suggestion, please?
Thank you for your time.
Regards,

Christian

**Comment by amrragab8080** [comment]
The screenshot is not the expected output of the S3 bucket. In the documentation did you sync the github directory with a s3 bucket. All the files and assests should be there.
![Screen Shot 2019-04-08 at 8 55 35 AM](https://user-images.githubusercontent.com/38997602/55725708-39dd6a80-59dc-11e9-80fc-1680a0b3c3c1.png)
