### ISSUE TITLE
Output files not getting generated

### ISSUE THREAD

**Issue by stephen-thomas** [aws-samples/aws-plugin-for-slurm#5]
After submitting jobs using sbatch I would expect the output logs to write to my current directory by default.

Even after adding this to my Job the output is not being written.
#SBATCH -o /nfs/output.%a.out # STDOUT

Any insight on configuring output files?

**Comment by amrragab8080** [comment]
The reason is that the setup doesnt include a shared fs between the headnode and compute. The output is actually saved on the compute node. It would be simple to include EFS, FSx, etc. As a mount point for a shared file system in the user-data field above line 37
https://github.com/aws-samples/aws-plugin-for-slurm/blob/933542a938abfc9140908bea359d399ef8dc813d/slurm-aws-startup.sh#L37

 Alternatively you can modify your job output scripts to write the output to S3.

**Comment by stephen-thomas** [comment]
Thanks a bunch for the quick reply! Two followup questions.

1. After creating an EFS the required security group it would need to be in would be that of the cluster, correct?
2. For your bottom 'Alternatively' statement, how would you export the logs to s3 in this way? Would you include something like an 'aws s3 cp /var/logs <dest>' at the end of your code?

**Comment by amrragab8080** [comment]
> Thanks a bunch for the quick reply! Two followup questions.
> 
> 1. After creating an EFS the required security group it would need to be in would be that of the cluster, correct?
- That is correct the `ClusterSG` would be the one you want to use.

> 2. For your bottom 'Alternatively' statement, how would you export the logs to s3 in this way? Would you include something like an 'aws s3 cp /var/logs ' at the end of your code?
- Its workload dependent - if your workflow can compress or package the output into a single file it would be a simple `aws s3 cp`, however if you want to sync an output job directory then you need to pass `--recursive`

**Comment by stephen-thomas** [comment]
Feel free to close issue. Thank you for answering questions.

**Comment by stephen-thomas** [comment]
Actually, sorry, one final question. 

Does slurm-aws-startup.sh execute directly from the headnode? As in, if I add the extra 'user-data' bits to the head nodes version of this file will that immediately change future worker nodes?

**Comment by amrragab8080** [comment]
> Actually, sorry, one final question.
> 
> Does slurm-aws-startup.sh execute directly from the headnode? As in, if I add the extra 'user-data' bits to the head nodes version of this file will that immediately change future worker nodes?

That is correct it will change future worker nodes. The user-data is added to the underlying compute node AMI at boot
