### ISSUE TITLE
System Diagram in README.md of aws-samples/ repository should not show EFS.

### ISSUE THREAD

**Issue by stephen-thomas** [aws-samples/aws-plugin-for-slurm#6]
I find it misleading that the system diagram shows an EFS volume in the architecture diagram as this is the first thing someone would see upon entering the repository.

I think that it should show the /nfs/ configuration instead as that is setup by default.

**Comment by amrragab8080** [comment]
The statement under the diagram is sufficient in stating that the EFS mount point is optional. Alternatively you can use FSx or a roll your own NFS. The diagram shows what is possible.
