### ISSUE TITLE
Spot & Reserved Instance Feasibility

### ISSUE THREAD

**Issue by stephen-thomas** [aws-samples/aws-plugin-for-slurm#7]
I have two questions 

What is the process like for connecting reserved instances manually to the cluster? Should I follow the aws-cluster-startup.sh script manually?

Is it feasible to run the worker nodes as spot instances? How does this setup handle node failures?

**Comment by amrragab8080** [comment]
For reserved instances, you dont have to anything as RIs are an accounting/billing construct. Just change the instance types in the slurm-aws-startup.sh script to match which RIs you have setup in your account.
```
   if [[ $host == *ip-10-0-1* ]]; then
      export AWS_SUBNET_ID=@PRIVATE1@
      aws_startup $host $private_ip c4.2xlarge
   elif [[ $host == *ip-10-0-2* ]]; then
      export AWS_SUBNET_ID=@PRIVATE2@
      aws_startup $host $private_ip c4.2xlarge
   elif [[ $host == *ip-10-0-3* ]]; then
      export AWS_SUBNET_ID=@PRIVATE3@
      aws_startup $host $private_ip c4.2xlarge
   fi
```
It is possible to invoke it with Spot, future updates will have this support
